spring:
  application:
    name : AdminMs
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
  cloud:
    config:
      enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8084
management:
  endpoints:
    web:
      exposure:
        include: info
logging:
  level:
    org.springframework.web.reactive.function.client: DEBUG
    org.apache.http: DEBUG
    io.netty: DEBUG
